# Generated by Django 5.2.13 on 2026-04-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseBJJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre corto de la clase (ej. BJJ Fundamentos, No-Gi).', max_length=100)),
                ('fecha_hora_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la clase.')),
                ('capacidad_maxima', models.PositiveIntegerField(default=20, help_text='Número máximo de personas que pueden asistir a la clase.')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas en que se guardó este registro.')),
                ('clase', models.ForeignKey(help_text='La clase de BJJ a la que asiste el deportista.', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.clasebjj')),
            ],
        ),
    ]
