# Generated by Django 5.2.13 on 2026-04-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasebjj',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=30, help_text='Número máximo de personas que pueden asistir a la clase.'),
        ),
    ]
