# Generated by Django 5.2.13 on 2026-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_clasebjj_capacidad_maxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasebjj',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o detalles adicionales sobre la sesión.', null=True),
        ),
        migrations.AddField(
            model_name='clasebjj',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la clase.', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ESPERA', 'Lista de Espera')], default='CONFIRMADA', help_text='Estado actual de la reserva gestionando aforo y lista de espera.', max_length=20),
        ),
    ]
