# Generated by Django 5.2.13 on 2026-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_clasebjj_descripcion_clasebjj_fecha_hora_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(default='🥋', max_length=50)),
                ('hora_inicio', models.TimeField(help_text='Hora de comienzo por defecto.')),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('capacidad_maxima', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='clasebjj',
            name='icono',
            field=models.CharField(default='🥋', help_text='Icono visual para la clase (emoji o nombre de icono).', max_length=50),
        ),
    ]
