# Generated by Django 5.2.13 on 2026-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_plantillaclase_clasebjj_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasebjj',
            name='categoria_acceso',
            field=models.CharField(choices=[('ADULTO', 'Solo Adultos'), ('JUVENIL', 'Solo Juveniles'), ('INFANTIL', 'Solo Infantiles')], default='ADULTO', help_text='Qué tipo de plan se requiere para esta clase.', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillaclase',
            name='categoria_acceso',
            field=models.CharField(choices=[('ADULTO', 'Solo Adultos'), ('JUVENIL', 'Solo Juveniles'), ('INFANTIL', 'Solo Infantiles')], default='ADULTO', max_length=20),
        ),
    ]
