# Generated by Django 5.2.13 on 2026-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_clasebjj_categoria_acceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasebjj',
            name='imagen_icono',
            field=models.FileField(blank=True, help_text='Imagen personalizada para la clase. Si se sube, tendrá prioridad sobre el icono emoji.', null=True, upload_to='iconos_clases/'),
        ),
        migrations.AddField(
            model_name='plantillaclase',
            name='imagen_icono',
            field=models.FileField(blank=True, help_text='Imagen personalizada para la plantilla.', null=True, upload_to='iconos_clases/'),
        ),
        migrations.AlterField(
            model_name='clasebjj',
            name='icono',
            field=models.CharField(default='🥋', help_text='Icono visual para la clase (emoji).', max_length=50),
        ),
    ]
