# Generated by Django 5.2.13 on 2026-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_clasebjj_imagen_icono_plantillaclase_imagen_icono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasebjj',
            name='icono',
            field=models.CharField(blank=True, help_text='Icono visual opcional (emoji).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clasebjj',
            name='imagen_icono',
            field=models.FileField(blank=True, help_text='Imagen personalizada para la clase.', null=True, upload_to='iconos_clases/'),
        ),
        migrations.AlterField(
            model_name='plantillaclase',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
