# Generated by Django 5.2.13 on 2026-05-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_clasebjj_icono_alter_clasebjj_imagen_icono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('badge', models.CharField(help_text='Etiqueta superior (ej: TÉCNICA, INTENSO).', max_length=50)),
                ('imagen', models.FileField(blank=True, help_text='Imagen de fondo para la tarjeta.', null=True, upload_to='actividades/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la web.')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
