# Generated by Django 5.2.13 on 2026-05-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tallas', models.CharField(blank=True, help_text='Ej: A0, A1, A2 o S, M, L', max_length=100, null=True)),
                ('estado_stock', models.CharField(choices=[('IN_STOCK', 'En Stock'), ('LOW_STOCK', 'Últimas tallas'), ('OUT_OF_STOCK', 'Agotado')], default='IN_STOCK', max_length=20)),
                ('imagen', models.FileField(blank=True, help_text='Imagen del producto.', null=True, upload_to='productos/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
