# Generated by Django 5.2.13 on 2026-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRepaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('archivo_video', models.FileField(help_text='Archivo de vídeo (mp4, webm, etc.)', upload_to='videos/')),
                ('miniatura', models.ImageField(blank=True, help_text='Imagen de previsualización para el vídeo.', null=True, upload_to='videos/thumbnails/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vídeo de Repaso',
                'verbose_name_plural': 'Vídeos de Repaso',
                'ordering': ['-fecha_publicacion', 'orden', 'id'],
            },
        ),
    ]
