# Generated by Django 5.2.13 on 2026-04-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='email',
            field=models.EmailField(help_text='Correo electrónico de contacto y recepción de notificaciones.', max_length=254, unique=True),
        ),
    ]
