# Generated by Django 5.2.13 on 2026-04-26 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_deportista_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, help_text='IBAN o cuenta (solo lo ve el admin).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Útil para determinar automáticamente si es Adulto, Juvenil o Niño.', null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='grados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Grados en el cinturón del atleta (solo lo ve el admin).'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='id_interno',
            field=models.CharField(blank=True, help_text='ID interno (modificable) asignado por el club.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='nif',
            field=models.CharField(blank=True, help_text='DNI/NIF. Los menores usan el de sus padres (puede haber duplicados por familia).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='padre_tutor',
            field=models.ForeignKey(blank=True, help_text='Relación Adulto -> Niños. Determina quién administra el perfil de un menor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deportista',
            name='plan_activo',
            field=models.BooleanField(default=False, help_text='El admin activa manualmente el plan. Sin esto a True, no puede reservar.'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='tipo_plan',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('FAMILIAR', 'Familiar')], max_length=50, null=True),
        ),
    ]
