# Generated by Django 5.2.13 on 2026-04-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_deportista_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='fecha_ultima_graduacion',
            field=models.DateField(blank=True, help_text='Auto-fecha. Se actualiza sola si el profesor cambia el cinturón o los grados.', null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='cinturon',
            field=models.CharField(choices=[('Blanco', 'Blanco'), ('Azul', 'Azul'), ('Morado', 'Morado'), ('Marrón', 'Marrón'), ('Negro', 'Negro'), ('Gris', 'Gris'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Verde', 'Verde')], default='Blanco', help_text='Grado o cinturón actual del deportista.', max_length=50),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='grados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Grados en el cinturón del atleta (0 a 4).'),
        ),
    ]
