# Generated by Django 5.2.13 on 2026-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_deportista_fecha_ultima_graduacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='es_familiar',
            field=models.BooleanField(default=False, help_text='Si es True, el deportista tiene un plan Familiar (descuento del 50%% para ambos familiares).'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tipo_plan',
            field=models.CharField(blank=True, choices=[('ADULTO', 'Mensual Adulto'), ('JUVENIL', 'Mensual Juvenil'), ('INFANTIL', 'Mensual Infantil')], help_text='Categoría del plan mensual según la edad del deportista.', max_length=50, null=True),
        ),
    ]
