# Generated by Django 5.2.13 on 2026-04-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_deportista_es_familiar_alter_deportista_tipo_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio mensual normal', max_digits=6)),
                ('beneficios', models.TextField(help_text='Lista de beneficios separados por comas o saltos de línea')),
                ('categoria_edad', models.CharField(choices=[('ADULTO', 'Adulto (18+)'), ('JUVENIL', 'Juvenil (14-17)'), ('INFANTIL', 'Infantil (<14)')], default='ADULTO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tipo_plan',
            field=models.ForeignKey(blank=True, help_text='Plan mensual asignado al deportista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.plan'),
        ),
    ]
