# Generated by Django 5.2.13 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_plan_alter_deportista_tipo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CUENTA', 'Cuenta')], default='EFECTIVO', help_text='Método de pago preferente del deportista.', max_length=20),
        ),
    ]
