# Generated by Django 5.2.13 on 2026-05-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_deportista_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_global', models.BooleanField(default=False)),
                ('leida', models.BooleanField(default=False, help_text='Solo aplica para notificaciones personales.')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Si está vacío y es_global es True, llega a todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_personales', to=settings.AUTH_USER_MODEL)),
                ('leida_por', models.ManyToManyField(blank=True, help_text='Track de quién ha leído la notificación global.', related_name='notificaciones_globales_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
