# Generated by Django 5.2.13 on 2026-05-10 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, help_text='Fuerza al usuario a cambiar su contraseña al hacer login.'),
        ),
        migrations.CreateModel(
            name='SolicitudReseteoPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reseteo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Reseteo',
                'verbose_name_plural': 'Solicitudes de Reseteo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
