# Generated by Django 5.2.13 on 2026-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_deportista_requiere_cambio_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Lista de beneficios separados por comas o saltos de línea'),
        ),
    ]
