# Generated by Django 5.2.13 on 2026-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_plan_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='categoria_edad',
            field=models.CharField(choices=[('ADULTO', 'Adulto (+18)'), ('JUVENIL', 'Juvenil (10-17)'), ('INFANTIL', 'Infantil (4-9)')], default='ADULTO', max_length=20),
        ),
    ]
